# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Proyecto.ui'
#
# Created: Sun Sep 14 17:39:28 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Main(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(490, 528)
        self.verticalLayoutWidget = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 491, 521))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.comboDia = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboDia.setObjectName(_fromUtf8("comboDia"))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.comboDia.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboDia)
        self.comboMes = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboMes.setObjectName(_fromUtf8("comboMes"))
        self.comboMes.addItem(_fromUtf8(""))
        self.comboMes.addItem(_fromUtf8(""))
        self.comboMes.addItem(_fromUtf8(""))
        self.comboMes.addItem(_fromUtf8(""))
        self.comboMes.addItem(_fromUtf8(""))
        self.comboMes.addItem(_fromUtf8(""))
        self.comboMes.addItem(_fromUtf8(""))
        self.comboMes.addItem(_fromUtf8(""))
        self.comboMes.addItem(_fromUtf8(""))
        self.comboMes.addItem(_fromUtf8(""))
        self.comboMes.addItem(_fromUtf8(""))
        self.comboMes.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboMes)
        self.comboAnio = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboAnio.setObjectName(_fromUtf8("comboAnio"))
        self.comboAnio.addItem(_fromUtf8(""))
        self.comboAnio.addItem(_fromUtf8(""))
        self.comboAnio.addItem(_fromUtf8(""))
        self.comboAnio.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboAnio)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.comboHora = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboHora.setObjectName(_fromUtf8("comboHora"))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.comboHora.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.comboHora)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.comboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.comboBox)
        self.pushButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout.addWidget(self.pushButton_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "El Club app", None))
        self.label_2.setText(_translate("Dialog", "Ingrese el dia:", None))
        self.comboDia.setItemText(0, _translate("Dialog", "1", None))
        self.comboDia.setItemText(1, _translate("Dialog", "2", None))
        self.comboDia.setItemText(2, _translate("Dialog", "3", None))
        self.comboDia.setItemText(3, _translate("Dialog", "4", None))
        self.comboDia.setItemText(4, _translate("Dialog", "5", None))
        self.comboDia.setItemText(5, _translate("Dialog", "6", None))
        self.comboDia.setItemText(6, _translate("Dialog", "7", None))
        self.comboDia.setItemText(7, _translate("Dialog", "8", None))
        self.comboDia.setItemText(8, _translate("Dialog", "9", None))
        self.comboDia.setItemText(9, _translate("Dialog", "10", None))
        self.comboDia.setItemText(10, _translate("Dialog", "11", None))
        self.comboDia.setItemText(11, _translate("Dialog", "12", None))
        self.comboDia.setItemText(12, _translate("Dialog", "13", None))
        self.comboDia.setItemText(13, _translate("Dialog", "14", None))
        self.comboDia.setItemText(14, _translate("Dialog", "15", None))
        self.comboDia.setItemText(15, _translate("Dialog", "16", None))
        self.comboDia.setItemText(16, _translate("Dialog", "17", None))
        self.comboDia.setItemText(17, _translate("Dialog", "18", None))
        self.comboDia.setItemText(18, _translate("Dialog", "19", None))
        self.comboDia.setItemText(19, _translate("Dialog", "20", None))
        self.comboDia.setItemText(20, _translate("Dialog", "21", None))
        self.comboDia.setItemText(21, _translate("Dialog", "22", None))
        self.comboDia.setItemText(22, _translate("Dialog", "23", None))
        self.comboDia.setItemText(23, _translate("Dialog", "24", None))
        self.comboDia.setItemText(24, _translate("Dialog", "25", None))
        self.comboDia.setItemText(25, _translate("Dialog", "26", None))
        self.comboDia.setItemText(26, _translate("Dialog", "27", None))
        self.comboDia.setItemText(27, _translate("Dialog", "28", None))
        self.comboDia.setItemText(28, _translate("Dialog", "29", None))
        self.comboDia.setItemText(29, _translate("Dialog", "30", None))
        self.comboDia.setItemText(30, _translate("Dialog", "31", None))
        self.comboMes.setItemText(0, _translate("Dialog", "1", None))
        self.comboMes.setItemText(1, _translate("Dialog", "2", None))
        self.comboMes.setItemText(2, _translate("Dialog", "3", None))
        self.comboMes.setItemText(3, _translate("Dialog", "4", None))
        self.comboMes.setItemText(4, _translate("Dialog", "5", None))
        self.comboMes.setItemText(5, _translate("Dialog", "6", None))
        self.comboMes.setItemText(6, _translate("Dialog", "7", None))
        self.comboMes.setItemText(7, _translate("Dialog", "8", None))
        self.comboMes.setItemText(8, _translate("Dialog", "9", None))
        self.comboMes.setItemText(9, _translate("Dialog", "10", None))
        self.comboMes.setItemText(10, _translate("Dialog", "11", None))
        self.comboMes.setItemText(11, _translate("Dialog", "12", None))
        self.comboAnio.setItemText(0, _translate("Dialog", "2014", None))
        self.comboAnio.setItemText(1, _translate("Dialog", "2015", None))
        self.comboAnio.setItemText(2, _translate("Dialog", "2016", None))
        self.comboAnio.setItemText(3, _translate("Dialog", "2017", None))
        self.label_3.setText(_translate("Dialog", "Ingrese la hora:", None))
        self.comboHora.setItemText(0, _translate("Dialog", "01", None))
        self.comboHora.setItemText(1, _translate("Dialog", "02", None))
        self.comboHora.setItemText(2, _translate("Dialog", "03", None))
        self.comboHora.setItemText(3, _translate("Dialog", "04", None))
        self.comboHora.setItemText(4, _translate("Dialog", "05", None))
        self.comboHora.setItemText(5, _translate("Dialog", "06", None))
        self.comboHora.setItemText(6, _translate("Dialog", "07", None))
        self.comboHora.setItemText(7, _translate("Dialog", "08", None))
        self.comboHora.setItemText(8, _translate("Dialog", "09", None))
        self.comboHora.setItemText(9, _translate("Dialog", "10", None))
        self.comboHora.setItemText(10, _translate("Dialog", "11", None))
        self.comboHora.setItemText(11, _translate("Dialog", "12", None))
        self.comboHora.setItemText(12, _translate("Dialog", "13", None))
        self.comboHora.setItemText(13, _translate("Dialog", "14", None))
        self.comboHora.setItemText(14, _translate("Dialog", "15", None))
        self.comboHora.setItemText(15, _translate("Dialog", "16", None))
        self.comboHora.setItemText(16, _translate("Dialog", "17", None))
        self.comboHora.setItemText(17, _translate("Dialog", "18", None))
        self.comboHora.setItemText(18, _translate("Dialog", "19", None))
        self.comboHora.setItemText(19, _translate("Dialog", "20", None))
        self.comboHora.setItemText(20, _translate("Dialog", "21", None))
        self.comboHora.setItemText(21, _translate("Dialog", "22", None))
        self.comboHora.setItemText(22, _translate("Dialog", "23", None))
        self.comboHora.setItemText(23, _translate("Dialog", "00", None))
        self.label_5.setText(_translate("Dialog", "Ingrese el tipo de cancha:", None))
        self.comboBox.setItemText(0, _translate("Dialog", "Futbol", None))
        self.comboBox.setItemText(1, _translate("Dialog", "Tenis", None))
        self.comboBox.setItemText(2, _translate("Dialog", "Basquet", None))
        self.pushButton.setText(_translate("Dialog", "Buscar", None))
        self.pushButton_2.setText(_translate("Dialog", "Agregar un nuevo turno", None))
        self.pushButton_3.setText(_translate("Dialog", "Borrar un turno", None))

